{{- if .Values.grafana.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-prom-grafana
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0cb020fe620780b07
  storageClassName: grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-grafana
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: grafana
  volumeMode: Filesystem
  volumeName: pvc-prom-grafana
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
{{end}}